on:
  push:
    branches:
      - main

jobs:
  builds-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Deploy to Azure Web Apps
      uses: Azure/login@v2.1.0
      with:
      #Change the app-name to match what was provided to you in the publish settings file, this is in a naming covention of 'COURSENAME-STUDENTUID'
        app-name: 'cmst386-eallen63'
        slot-name: 'production'
      #Change the publish proflie to match what you named your secret setup in GitHub, example shown below
        publish-proflie: ${{ secrets.AppServiceCMST386 }}
      
            
